name = "allora-inference-function"
version = "1.0.0"

[deployment]
nodes = 1

[build]
dir = "build"
entry = "allora-inference-function_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "allora-inference-function.wasm"
command = "npm run build:release"
